<?php

module_load_include('inc', 'GuLib', '/include/autoload');
Gulei\Autoloader::register(__DIR__);

require_once __DIR__ . '/lib/autoload.inc';

function amapi_menu()
{
  $items = array();

  $items['amapi/test'] = array(
    'page callback' => 'amapi_test',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function amapi_test()
{
//  include __DIR__ . '/lib/RequestReportSample.php';
//  include __DIR__ . '/lib/GetReportRequestListSample.php';
//  include __DIR__ . '/lib/GetReportListSample.php';
//  include __DIR__ . '/lib/GetReportSample.php';

  $prov = new Amapi\Provider\ActiveListing();
  dpr($prov->getData());
  return '';
}