<?php

module_load_include('inc', 'GuLib', 'autoload');
\Gulei\Autoloader::register(__DIR__);

function oerp_stock_menu(){
  $item = array();
  return $item;
}

function oerp_stock_block($op = 'list', $delta = 0, $edit = array()){
  switch($op){
    case 'list':
      $blocks[0]['info'] = t('Stock Mngn');
      return $blocks;
      
    case 'view':
      $items = array(
        array(
          'data' => Oerp\Link\Tree::create('Input / Output', 'x_stock.picking.tree')
        ),
        array(
          'data' => Oerp\Link\Tree::create('Periodical Inventory', 'x_stock.inventory.tree')
        ),
        array(
          'data' => Oerp\Link\Tree::create('Minimum Stock Rules', 'stock.warehouse.orderpoint.tree')
        ),
      );
      
      $block['subject'] = t('Stock Mngn');
      $block['content'] = theme('item_list', $items, null, 'ul', array('class' => 'menu'));
      return $block;
  }
}