<?php

function oerp_delivery_schema(){
  $schema = array();

  $schema['oerp_delivery_output'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'rid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'date_create' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'date_done' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'seller' => array(
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
      ),
      'sku'=> array(
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
      ),
      'qty' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'carrier' => array(
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
      ),
      'country' => array(
        'type' => 'varchar',
        'length' => 60,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );
  return $schema;
}

function oerp_delivery_install(){
  drupal_install_schema('oerp_delivery');
}

function oerp_delivery_uninstall(){
  drupal_uninstall_schema('oerp_delivery');
}