<?php

module_load_include('module', 'GuLib');
\Gulei\Autoloader::register(__DIR__);

function listing_menu()
{
  $items = array();
  $items['listing/check'] = array(
    'title' => 'Check Online Listings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('listing_check_form'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['listing/rakuten/check/js'] = array(
    'page callback' => 'listing_rakuten_check_js',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function listing_check_form(&$form_state)
{
  $ctrl = new \Listing\Page\Check($form_state);
  return $ctrl->hook_form($form_state);
}

function listing_check_form_submit($form, &$form_state)
{
  $ctrl = new \Listing\Page\Check($form_state);
  return $ctrl->hook_form_submit($form, $form_state);
}

function listing_rakuten_check_js()
{
  $chk = new \Listing\Checker\Rakuten();
  return drupal_json($chk->checkOnline($_POST['href']));
}