<?php
use Ebapi as E;

module_load_include('module', 'ebapi');
\Gulei\Autoloader::register(__DIR__);

function ebapi_fitment_menu()
{
  $items = array();

  $items['ebapi/fitment/reload'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ebapi_fitment_reload_form'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/fitment/select/js'] = array(
    'page callback' => 'ebapi_fitment_select_js',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/fitment/list/js'] = array(
    'page callback' => 'ebapi_fitment_list_js',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/fitment/select'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ebapi_fitment_select_form'),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/%/fitment/edit'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ebapi_fitment_edit_form', 1),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/%/sku_fitment/edit'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ebapi_sku_fitment_edit_form', 1),
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/fitment/myselling/js'] = array(
    'page callback' => 'ebapi_fitment_myselling_js',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  $items['ebapi/fitment/import/js'] = array(
    'page callback' => 'ebapi_fitment_import_js',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function ebapi_fitment_theme(){
  return array(
    'ebapi_fitment_selector' => array(
      'arguments' => array(),
    ),
  );
}

function ebapi_fitment_elements(){
  return array(
    'ebapi_fitment_selector' => array(
      '#input' => true,
      '#value' => null,
      '#process' => array('ebapi_fitment_selector_process'),
    ),
  );
}

function ebapi_fitment_selector_process($ele, $edit, &$form_state, $form)
{
  $ctrl = new \Ebapi\Compatibility\_List($form_state);
  $ele = array_merge($ele, $ctrl->getFormEntry($form_state));
  $ele['#prefix'] = '<div id="ebapi-compatibility-wrapper">';
  $ele['#suffix'] = '</div>';
  return $ele;
}

function theme_ebapi_fitment_selector($ele)
{
  return $ele['#children'];
}

function ebapi_fitment_reload_form(&$form_state)
{
  $l = new \Ebapi\Csv\SerialLoader();
  return $l->getSourceEntry();
}

function ebapi_fitment_reload_form_submit($form, &$form_state)
{
  $l = new \Ebapi\Csv\SerialLoader();
  $l->reload($form_state['values']['source']);
}

function ebapi_fitment_edit_form(&$form_state, $accnt)
{
  $form = array();
  $form['title'] = array(
    '#type' => 'markup',
    '#value' => "<h1><em>$accnt</em> - Compatibility Editor</h1>",
  );

  $form['fitment'] = array(
    '#type' => 'ebapi_fitment_selector'
  );

  $t = new \Ebapi\Page\MySelling\Fitment($form_state);
  $form['listings'] = $t->hook_form($form_state, $accnt);
  
  drupal_add_css(drupal_get_path('module', 'ebapi') . '/ebapi.css');
  return $form;
}

function ebapi_sku_fitment_edit_form(&$form_state, $accnt)
{
  $form = array();
  $form['title'] = array(
    '#type' => 'markup',
    '#value' => "<h1><em>$accnt</em> - Compatibility Editor</h1>",
  );

  $form['fitment'] = array(
    '#type' => 'ebapi_fitment_selector'
  );

  $t = new \Ebapi\Page\MySelling\Fitment($form_state);
  $form['listings'] = $t->hook_form($form_state, $accnt);

  drupal_add_css(drupal_get_path('module', 'ebapi') . '/ebapi.css');
  return $form;
}

function ebapi_fitment_edit_form_submit($form, &$form_state)
{
  $vals = $form_state['values'];
  $selFitment = (array)json_decode($vals['selected']);
  $comp_send = array();

  $isSiteUk = $_GET['site'] == 'UK';

  foreach(array_keys($selFitment) as $id){
    if ($isSiteUk) {
      $fit = new \Ebapi\Fitment\UK\Helper();
      $flds = array('Make', 'Model', 'Variant', 'BodyStyle', 'Type', 'Engine');
    }
    else {
      $fit = new \Ebapi\Fitment\Motors\Helper();
      $flds = array('Make', 'Model', 'Submodel', 'Body', 'NumDoors', 'Trim', 'Year', 'Engine');
    }

    if($data = $fit->queryById($id)){
      $rec = array();
      foreach($flds as $fld){
        if ($isSiteUk && $fld == 'Make') {
          $rec['NameValueList'][] = array(
            'Name' => 'Car Make',
            'Value' => $data->$fld,
          );
        }
        else {
          $rec['NameValueList'][] = array(
            'Name' => $fld,
            'Value' => $data->$fld,
          );
        }
      }

      if ($isSiteUk) {
        $rec = $fit->addCompaNote($id, $rec);
      }
      $comp_send['Compatibility'][] = $rec;
    }
  }
//  print_r($comp_send);die;

  $comp_send['ReplaceAll'] = 'true';
  $l_count = 0;
  $ig_count = 0;

  $Accnt = new \Ebapi\Account\Helper($vals['accnt']);

  foreach($_POST as $name => $val)
  {
    if(preg_match('/^sel-(.*)/', $name, $m) && $val){
      $item = Services_Ebay::loadModel('Item', $m[1], $Accnt->getSession());
      $item->Get();
      $rec = $item->toArray();

      $avail_sites = array(
        'eBayMotors',
        'UK',
      );

      if (in_array($rec['Site'], $avail_sites, true)) {
        $item->ItemCompatibilityList = $comp_send;

        if ($isSiteUk) {
          $returnPolicy = $item->ReturnPolicy;
          $returnPolicy['ShippingCostPaidByOption'] = 'Buyer';
          $item->ReturnPolicy = $returnPolicy;
        }

        try {
          $rs = $item->Revise();
        }
        catch (Exception $e) {
          /* Do Nothing */
        }
        $l_count++;
      }
      else{
        $ig_count++;
      }
    }
  }

  drupal_set_message('Updated Fitments of ' . $l_count . ' listing(s).');
  drupal_set_message('Ignored ' . $ig_count . ' listing(s) not on eBayMotors.');
  
  $form_state['rebuild'] = true;
}

function ebapi_fitment_select_form(&$form_state)
{
  $ctrl = new \Ebapi\Compatibility\_List($form_state);
  return $ctrl->getFormEntry();
}

function ebapi_fitment_select_js()
{
  $form_id = 'ebapi_fitment_select_form';
  $form_state['values'] = $_POST;
  $form = ebapi_fitment_select_form($form_state);

  drupal_process_form($form_id, $form, $form_state);
  $output = theme('status_messages') . drupal_render($form);

  drupal_json(array('status' => TRUE, 'data' => $output));
}

function ebapi_fitment_list_js()
{
  $form_id = 'ebapi_fitment_select_form';
  $form_state['values'] = $_POST;
  $form_state['list_only'] = true;
  $form = ebapi_fitment_select_form($form_state);

  drupal_process_form($form_id, $form, $form_state);
  $output = theme('status_messages') . drupal_render($form);

  drupal_json(array('status' => TRUE, 'data' => $output));
}

function ebapi_fitment_import_js()
{
  $ItemID = $_POST['ItemID'];
  if ($_POST['site'] == 'UK') {
    $fitment = new \Ebapi\Fitment\UK\Helper();
  }
  else {
    $fitment = new \Ebapi\Fitment\Motors\Helper();
  }
  $resp = $fitment->queryByItemID($_POST['accnt'], $ItemID);
  return drupal_json($resp);
}


function ebapi_fitment_myselling_form(&$form_state, $accnt)
{
  $p = new \Ebapi\Page\MySelling\Fitment($form_state);
  return $p->hook_form($form_state, $accnt);
}

function ebapi_fitment_myselling_form_submit($form, &$form_state)
{
  $p = new \Ebapi\Page\MySelling\Fitment($form_state);
  $p->hook_form_submit($form, $form_state);
}

function ebapi_fitment_myselling_js()
{
  $p = new \Ebapi\Page\MySelling\Fitment(null);
  return $p->hook_form_js('ebai_fitment_myselling_form');
}