<?php

module_load_include('module', 'oerp');
\Gulei\Autoloader::register(__DIR__);

function oerp_purchase_menu()
{
  $item = array();

  $item['oerp/purchase_mngn/compute_rop'] = array(
    'page callback' => 'oerp_purchase_computeRop',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  return $item;
}

function oerp_purchase_block($op = 'list', $delta = 0, $edit = array())
{
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Purchase Mngn');
      return $blocks;

    case 'view':
      $items = array(
        array(
          'data' => Gulei\Link\Page::create('Purchase Orders', "Oerp\\Purchase\\Page\\Orders"),
          'children' => array(
            array(Gulei\Link\Page::create('Draft', "Oerp\\Purchase\\Page\\Orders\\Draft")),
          ),
        ),
        array(
          'data' => Oerp\Link\Tree::create(
            'Exception Procurement', 'mrp.procurement.tree', array('cri' => '[["state","=","exception"]]')
          ),
        ),
        array(
          'data' => l(
            'Compute Orderpoints',
            'oerp/purchase_mngn/compute_rop'
          )
        )
      );

      $block['subject'] = t('Purchase Mngn');
      $block['content'] = theme('item_list', $items, null, 'ul', array('class' => 'menu'));
      return $block;
  }
}

function oerp_purchase_computeRop(){
  $wid = \Oerp\Query\Basic::_execute(
    array('mrp.procurement.orderpoint.compute'),
    'create',
    'wizard'
  );

  $resp = \Oerp\Query\Basic::_execute(
    array(
         (int)$wid,
         array(
           'form' => array(
             'automatic' => 0,
           )
         ),
         'compute'
    ),
    'execute',
    'wizard'
  );

  if($resp['state'] == 'end'){
    drupal_set_message('Orderpoints computed. The result may not show immediately, please check here again later.');
  }
  else{
    drupal_set_message('Orderpoint computation failed.', 'error');
  }

  drupal_goto('http://192.168.11.7/www/Gyoumu/dev-product_data/?q=gulib/form&n=Oerp%5CPurchase%5CPage%5COrders');
}